# Generated by Django 5.2.15 on 2026-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_recipient_remove_notification_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RETRYING', 'Retrying'), ('DEAD_LETTER', 'Dead-letter')], default='PENDING', max_length=12),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_00072e_idx'),
        ),
    ]
