# Generated by Django 5.2.15 on 2026-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_delivery_next_attempt_at_alter_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
    ]
