# Generated by Django 5.2.15 on 2026-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_delivery_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
