# Generated by Django 5.2.15 on 2026-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_scheduled_for_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RETRYING', 'Retrying'), ('THROTTLED', 'Throttled'), ('DEAD_LETTER', 'Dead-letter')], default='PENDING', max_length=12),
        ),
    ]
